const CONSTANTS = {
  CURRENCY_CODE: "USD",
  COMPANY_NAME: "TechCorp Solutions",
  OTP_EXPIRATION_MINUTES: 10,
  OTP_COUNTDOWN_SECONDS: 60,
  DEFAULT_BATCH_SIZE: 200,
  DEFAULT_QUERY_LIMIT: 100,
  DASHBOARD_QUERY_LIMIT: 50,
  ROLE_HR_ADMIN: "HR Admin",
  ROLE_EMPLOYEE: "Employee",
  ROLE_MANAGER: "Manager",
  ROLE_PROJECT_MANAGER: "Project Manager"
};

export { CONSTANTS };